### ISSUE TITLE
Test preconditions

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/octopus#27]
**Description**
A test definition might have a requirement on specific resources to be existent in order to run. That requirement exists for multiple test definitions. As an example take a look at the `testing.sh` of kyma where the suite execution requires a helm broker testing bundle to be configured upfront. That configuration is not part of the default kyma installation but many test definitions require them and it should be configured upfront as part of the suite execution.
Another example is the dex static password requirement defined in the same script in Kyma. Here, the test needs to be sure that a specific condition is established, otherwise the test should be skipped.

**Reasons**
To remove Kyma's `testing.sh` in order to use plain octopus tooling, any workarounds needs to be solved. The mentioned two examples are the specific problems to be solved in a generic way. However, it is a general problem to solve as it is a common pattern that tests have preconditions which are either established in a setup phase or will lead to a skipping of the test.

**Details**
A solution might look like this:

A test definition is expressing a condition by a label on the TestDefinition resource like:
```
labels:
  requires-testing-bundle=true
  requires-test-user=true
```

When creating a TestSuite, by default `requires` labels are not satisfied and the TestSuite will not execute any test having a `requires` label, instead it will set it's status to `skipped` with a reason text.

In order to satisfy a `requires` we need a new CRD TestRequirement, specifying the label condition and a Job (or simply in-line script?) to evaluate the condition. Optional it can define a setUp and tearDown Job (or simply in-line script?) in order to satisfy a condition.

```
kind: TestRequirement
metadata:
  name: testing-bundle
spec:
  evaluationExpression: "kubectl get configmap testing-bundles-repos"
  setupExpression: "kubectl create configmap testing-bundles-repos  --from-literal=...; kubectl label configmap testing-bundles-repos helm-broker-repo=true"
  tearDownExpression: "kubectl delete configmap testing-bundles-repos
```

```
kind: TestRequirement
metadata:
  name: testing-user
spec:
  evaluationExpression: "${kc} get cm dex-config -n kyma-system -ojsonpath="{.data}" | grep --silent "#__STATIC_PASSWORDS__"
```

The TestSuite will find all TestRequirement resources in a cluster and now can evaluate the `requires` label. With that, test requirements might be already satisfied by the resources present on the cluster. Additionally, a `TestRequirement` can have a setup which will turn the evaluation into success after execution. On TestSuite deletion, the tearDown expressions should be executed.
